[project]
name = "weather-api"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "httpx>=0.28.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
