[project]
name = "weather-api"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
